# general settings
name: llbnetv73_mask-0.1_stage2-decoder-fs_bfpu_depth4_last-mask_simo_v2
model_type: Local2StageModel
num_gpu: 2
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: LOLBlurDataset_Train
    type: PairedLocalImageDataset
    dataroot_gt: /data///datasets/relo/image/train/sharp,/data///datasets/lolblur/high_sharp_scaled
    dataroot_lq: /data///datasets/relo/image/train/blur,/data///datasets/lolblur/low_blur_noise
    filename_tmpl: '{}'
    io_backend:
      type: disk

    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    use_flip: true
    use_rot: true
    crop_size: 256

    use_shuffle: true
    batch_size_per_gpu: &bsz 4
    num_worker_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

    prefetch_mode: cpu
    num_prefetch_queue: 4

  val:
    name: LOLBlurDataset_Test
    type: PairedLocalImageDataset
    dataroot_gt: /data///datasets/relo/image/test/sharp
    dataroot_lq: /data///datasets/relo/image/test/blur
    io_backend:
      type: disk

    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

# network structures
network_g:
  type: LLBNetv74


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 500000
    eta_min: !!float 1e-7

  # scheduler:
  #   type: CosineAnnealingRestartLR
  #   periods: [500000]
  #   restart_weights: [1]
  #   eta_min: !!float 1e-7

  total_iter: 500000
  warmup_iter: -1  # no warm up
  stage1_weight: 0.2
  stage2_weight: 0.8

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1.0
    reduction: mean

  mask_opt:
    type: MSELoss
    loss_weight: 0.1
    reduction: mean

  perceptual_opt:
    type: FFTWeightLoss
    loss_weight: 0.1
    reduction: mean

  ssim_opt:
    type: SSIMWeightLoss
    loss_weight: 1
    reduction: mean


# validation settings
val:
  val_freq: !!float 5e3
  save_img: True
  use_image: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

    w_ssim:
      type: calculate_weighted_ssim
      crop_border: 0
      test_y_channel: false

    w_psnr:
      type: calculate_weighted_psnr
      crop_border: 0
      test_y_channel: false
# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29520
